#remote_theme: minima #pages-themes/slate@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Identifying Market Patterns with StatsViz

author: 
 name: StatsViz Inc.

description: > 
  StatsViz helps investors and traders uncover seasonal and statistical patterns in the market. Perfect for traders and investors interested in adding a statistical perspective to their toolkit.

# theme: minima
remote_theme: jekyll/minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# link only to specific pages in the header 
header_pages:
  - index.md
  - [StatsViz](www.statsviz.com)

minima: 
  skin: auto

  social_links:
    # - { platform: github, user_url: "https://github.com/doomed51" }
    # - { platform: x, user_url: "https://x.com/inSenCite" }

